### ISSUE TITLE
load_bitfile.py fails with PYNQ Build Version 2.0

### ISSUE THREAD

**Issue by N35N0M** [maltanar/rosetta#2]
With the latest build available from PYNQ (https://github.com/Xilinx/PYNQ), and using Vivado 2016.4 to build, the setup fails at the load_bitfile.py part on the PYNQ board. @Belgaux diffed the previous PYNQ build to this one, and saw that there is a change from Xilinx in how the bitfile is parsed. One can either use the previous working image (V1.4), or use the fix that @Belgaux found and is reposted here: https://github.com/DMProAccelerator/setup/blob/master/pl.py

**Comment by nickfraser** [comment]
I believe in Pynq version 2.0 a tcl file with the same name as the bitfile containing the block diagram was required. I've provided one in #7 - this may also solve your issue.

**Comment by maltanar** [comment]
#7 has been merged and this should no longer be a problem.
